version: 0.2

phases:

  install:
    commands:
      # - "apt install unzip -y"
      # - "wget https://releases.hashicorp.com/terraform/0.11.14/terraform_0.11.14_linux_amd64.zip"
      # - "unzip terraform_0.11.14_linux_amd64.zip"
      # - "mv terraform /usr/local/bin/"
      # for Ubuntu build runtime
      # - wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
      # - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      # - sudo apt update && sudo apt install terraform
      # for Amazon Linux build runtime
      - sudo yum install -y yum-utils
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - sudo yum -y install terraform
  pre_build:
    commands:
      - terraform init

  build:
    commands:
      - terraform apply -auto-approve
      # - terraform destroy -auto-approve

  post_build:
    commands:
      - echo terraform apply completed on $(date)
      # - echo terraform destroy completed on $(date)